In [42]:
import numpy as np
import pandas as pd
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [43]:
a=pd.read_csv("svmfile.csv")

In [44]:
a.head(15)

age          job   marital            education  default housing loan  \
0    56    housemaid   married             basic.4y       no      no   no   
1    57     services   married          high.school  unknown      no   no   
2    37     services   married          high.school       no     yes   no   
3    40       admin.   married             basic.6y       no      no   no   
4    56     services   married          high.school       no      no  yes   
5    45     services   married             basic.9y  unknown      no   no   
6    59       admin.   married  professional.course       no      no   no   
7    41  blue-collar   married              unknown  unknown      no   no   
8    24   technician    single  professional.course       no     yes   no   
9    25     services    single          high.school       no     yes   no   
10   41  blue-collar   married              unknown  unknown      no   no   
11   25     services    single          high.school       no     yes   no   
12   29  blue-collar    single          high.school       no      no  yes   
13   57    housemaid  divorced             basic.4y       no     yes   no   
14   35  blue-collar   married             basic.6y       no     yes   no   

      contact month day_of_week  duration  campaign  pdays  previous  \
0   telephone   may         mon       261         1    999         0   
1   telephone   may         mon       149         1    999         0   
2   telephone   may         mon       226         1    999         0   
3   telephone   may         mon       151         1    999         0   
4   telephone   may         mon       307         1    999         0   
5   telephone   may         mon       198         1    999         0   
6   telephone   may         mon       139         1    999         0   
7   telephone   may         mon       217         1    999         0   
8   telephone   may         mon       380         1    999         0   
9   telephone   may         mon        50         1    999         0   
10  telephone   may         mon        55         1    999         0   
11  telephone   may         mon       222         1    999         0   
12  telephone   may         mon       137         1    999         0   
13  telephone   may         mon       293         1    999         0   
14  telephone   may         mon       146         1    999         0   

       poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0   nonexistent           1.1          93.994          -36.4      4.857   
1   nonexistent           1.1          93.994          -36.4      4.857   
2   nonexistent           1.1          93.994          -36.4      4.857   
3   nonexistent           1.1          93.994          -36.4      4.857   
4   nonexistent           1.1          93.994          -36.4      4.857   
5   nonexistent           1.1          93.994          -36.4      4.857   
6   nonexistent           1.1          93.994          -36.4      4.857   
7   nonexistent           1.1          93.994          -36.4      4.857   
8   nonexistent           1.1          93.994          -36.4      4.857   
9   nonexistent           1.1          93.994          -36.4      4.857   
10  nonexistent           1.1          93.994          -36.4      4.857   
11  nonexistent           1.1          93.994          -36.4      4.857   
12  nonexistent           1.1          93.994          -36.4      4.857   
13  nonexistent           1.1          93.994          -36.4      4.857   
14  nonexistent           1.1          93.994          -36.4      4.857   

    nr.employed   y  
0        5191.0  no  
1        5191.0  no  
2        5191.0  no  
3        5191.0  no  
4        5191.0  no  
5        5191.0  no  
6        5191.0  no  
7        5191.0  no  
8        5191.0  no  
9        5191.0  no  
10       5191.0  no  
11       5191.0  no  
12       5191.0  no  
13       5191.0  no  
14       5191.0  no

In [45]:
a.tail(15)

age          job   marital            education default housing loan  \
41173   62      retired   married    university.degree      no     yes   no   
41174   62      retired   married    university.degree      no     yes   no   
41175   34      student    single              unknown      no     yes   no   
41176   38    housemaid  divorced          high.school      no     yes  yes   
41177   57      retired   married  professional.course      no     yes   no   
41178   62      retired   married    university.degree      no      no   no   
41179   64      retired  divorced  professional.course      no     yes   no   
41180   36       admin.   married    university.degree      no      no   no   
41181   37       admin.   married    university.degree      no     yes   no   
41182   29   unemployed    single             basic.4y      no     yes   no   
41183   73      retired   married  professional.course      no     yes   no   
41184   46  blue-collar   married  professional.course      no      no   no   
41185   56      retired   married    university.degree      no     yes   no   
41186   44   technician   married  professional.course      no      no   no   
41187   74      retired   married  professional.course      no     yes   no   

        contact month day_of_week  duration  campaign  pdays  previous  \
41173  cellular   nov         thu       329         1    999         2   
41174  cellular   nov         thu       208         1      1         6   
41175  cellular   nov         thu       180         1    999         2   
41176  cellular   nov         thu       360         1    999         0   
41177  cellular   nov         thu       124         6    999         0   
41178  cellular   nov         thu       483         2      6         3   
41179  cellular   nov         fri       151         3    999         0   
41180  cellular   nov         fri       254         2    999         0   
41181  cellular   nov         fri       281         1    999         0   
41182  cellular   nov         fri       112         1      9         1   
41183  cellular   nov         fri       334         1    999         0   
41184  cellular   nov         fri       383         1    999         0   
41185  cellular   nov         fri       189         2    999         0   
41186  cellular   nov         fri       442         1    999         0   
41187  cellular   nov         fri       239         3    999         1   

          poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
41173      failure          -1.1          94.767          -50.8      1.031   
41174      success          -1.1          94.767          -50.8      1.031   
41175      failure          -1.1          94.767          -50.8      1.031   
41176  nonexistent          -1.1          94.767          -50.8      1.031   
41177  nonexistent          -1.1          94.767          -50.8      1.031   
41178      success          -1.1          94.767          -50.8      1.031   
41179  nonexistent          -1.1          94.767          -50.8      1.028   
41180  nonexistent          -1.1          94.767          -50.8      1.028   
41181  nonexistent          -1.1          94.767          -50.8      1.028   
41182      success          -1.1          94.767          -50.8      1.028   
41183  nonexistent          -1.1          94.767          -50.8      1.028   
41184  nonexistent          -1.1          94.767          -50.8      1.028   
41185  nonexistent          -1.1          94.767          -50.8      1.028   
41186  nonexistent          -1.1          94.767          -50.8      1.028   
41187      failure          -1.1          94.767          -50.8      1.028   

       nr.employed    y  
41173       4963.6  yes  
41174       4963.6  yes  
41175       4963.6   no  
41176       4963.6   no  
41177       4963.6   no  
41178       4963.6  yes  
41179       4963.6   no  
41180       4963.6   no  
41181       4963.6  yes  
41182       4963.6   no  
41183       4963.6  ye

In [46]:
a.shape

(41188, 21)

In [47]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [48]:
a.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [49]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
a[a.select_dtypes(include=["object"]).columns]=a[a.select_dtypes(include=["object"]).columns].apply(le.fit_transform)

In [50]:
# Negative values run the fit transform function individually
a["cons.conf.idx"]=le.fit_transform(a["cons.conf.idx"])
a["emp.var.rate"]=le.fit_transform(a["emp.var.rate"])

In [51]:
from sklearn.model_selection import train_test_split
a_train,a_test=train_test_split(a,test_size=0.2)

In [52]:
a_train_x=a_train.iloc[:,:-1]
a_train_y=a_train.iloc[:,-1]

In [53]:
a_test_x=a_test.iloc[:,:-1]
a_test_y=a_test.iloc[:,-1]

In [54]:
from sklearn.naive_bayes import MultinomialNB

In [55]:
n=MultinomialNB()

In [56]:
n.fit(a_train_x,a_train_y)

MultinomialNB()

In [57]:
pred=n.predict(a_test_x)

In [58]:
pred

array([1, 1, 0, ..., 0, 1, 0])

In [59]:
from sklearn.metrics import confusion_matrix
confusion_matrix(a_test_y,pred)

array([[6345,  984],
       [ 285,  624]], dtype=int64)

In [60]:
from sklearn.metrics import accuracy_score
accuracy_score(a_test_y,pred)

0.8459577567370721

In [66]:
from sklearn.svm import SVC
s=SVC(kernel="poly",degree=5)
s.fit(a_train_x,a_train_y)

SVC(degree=5, kernel='poly')

In [67]:
pred=s.predict(a_test_x)

In [68]:
pred

array([0, 1, 0, ..., 0, 0, 0])

In [69]:
confusion_matrix(a_test_y,pred)

array([[7215,  114],
       [ 705,  204]], dtype=int64)

In [70]:
accuracy_score(a_test_y,pred)

0.9005826656955572